# -*- coding: utf-8 -*-
"""Projeto de Extensão - Estácio

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XZoZWDwibARBRkPb3XviQ_tJC6RN23Ig
"""

import pandas as pd #Biblioteca pandas
import matplotlib.pyplot as plt #Biblioteca matplotlib

#Leitura dos dados

df = pd.read_csv("DadosDeCadaEstados.csv", sep=';') #variavel de armazenamentos dos dados
print("\n",df,"\n") #Imprime os dados

# Plote do gráfico
plt.pie(df['QNT_CASASDEAPOIO'], labels=df['ESTADOS'], autopct='%1.1f%%')
plt.title('Gráfico dos Dados das Quantidades de Casas \nde Apoio no Estado Nodestino')
plt.show()